use crate::parser::{CharacterData, GearItem};

/// Generate SimC input string for a character
pub fn generate_simc(character: &CharacterData) -> String {
    let mut simc = String::new();

    // Header
    simc.push_str("# SimC Input generated by EdgeRush LootMan\n");
    simc.push_str(&format!("{}=\"{}\"\n", character.class.to_lowercase(), character.name));
    simc.push_str(&format!("level={}\n", character.level));
    simc.push_str(&format!("race={}\n", character.race.as_deref().unwrap_or("unknown").to_lowercase()));
    simc.push_str("role=attack\n"); // TODO: Infer from spec
    simc.push_str(&format!("spec={}\n", character.spec.to_lowercase().replace(" ", "_")));
    
    if let Some(talents) = &character.talents {
        simc.push_str(&format!("talents={}\n", talents));
    }

    simc.push('\n');

    // Gear
    for item in &character.gear {
        let slot_name = convert_slot_name(&item.slot_name);
        if slot_name.is_empty() {
            continue;
        }

        let mut item_str = format!("{}=", slot_name);
        
        // SimC prefers name if available, but ID is sufficient
        // We generally don't have name in Rust struct currently, so start with comma implies ID-based
        item_str.push_str(",id=");
        item_str.push_str(&item.item_id.to_string());

        if let Some(enchant) = item.enchant_id {
            item_str.push_str(&format!(",enchant_id={}", enchant));
        }

        if !item.gem_ids.is_empty() {
             let gems: Vec<String> = item.gem_ids.iter().map(|id| id.to_string()).collect();
             item_str.push_str(&format!(",gem_id={}", gems.join("/")));
        }

        if !item.bonus_ids.is_empty() {
            let bonuses: Vec<String> = item.bonus_ids.iter().map(|id| id.to_string()).collect();
            item_str.push_str(&format!(",bonus_id={}", bonuses.join("/")));
        }

        item_str.push('\n');
        simc.push_str(&item_str);
    }

    simc
}

fn convert_slot_name(slot: &str) -> String {
    match slot {
        "Head" => "head",
        "Neck" => "neck",
        "Shoulder" => "shoulder",
        "Chest" => "chest",
        "Waist" => "waist",
        "Legs" => "legs",
        "Feet" => "feet",
        "Wrist" => "wrist",
        "Hands" => "hands",
        "Finger1" => "finger1",
        "Finger2" => "finger2",
        "Trinket1" => "trinket1",
        "Trinket2" => "trinket2",
        "Back" => "back",
        "MainHand" => "main_hand",
        "OffHand" => "off_hand",
        _ => "",
    }.to_string()
}
