ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_id VARCHAR(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS username VARCHAR(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS is_admin_mode BOOLEAN DEFAULT FALSE;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS request_id VARCHAR(255);
