spring:
  application:
    name: data-sync-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:edgerush}
    username: ${POSTGRES_USER:edgerush}
    password: ${POSTGRES_PASSWORD:edgerush}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    baseline-on-migrate: true

sync:
  cron: "0 0 4 * * *"
  run-on-startup: ${SYNC_RUN_ON_STARTUP:false}
  wowaudit:
    base-url: ${WOWAUDIT_BASE_URL:https://wowaudit.com}
    guild-profile-uri: ${WOWAUDIT_GUILD_URI:}
    api-key: ${WOWAUDIT_API_KEY:}

# FLPS Algorithm Configuration
flps:
  rms:
    attendance: 0.45      # Weight for Attendance Consistency Score in RMS
    mechanical: 0.35      # Weight for Mechanical Adherence Score in RMS
    preparation: 0.20     # Weight for External Preparation Score in RMS
  ipi:
    upgrade-value: 0.45   # Weight for upgrade value in IPI calculation
    tier-bonus: 0.35      # Weight for tier bonus in IPI calculation
    role-multiplier: 0.20 # Weight for role multiplier in IPI calculation
  role-multipliers:
    tank: 1.2             # Tank role gets 20% bonus (rare/critical role)
    healer: 1.1           # Healer role gets 10% bonus (important role)
    dps: 1.0              # DPS baseline multiplier
  thresholds:
    eligibility-attendance: 0.8     # Minimum attendance % for loot eligibility
    eligibility-activity: 0.0       # Minimum activity score for eligibility
    recency-decay-days: 30          # Days for recency decay factor calculation
    max-attendance-bonus: 1.0       # Maximum attendance score cap
    min-mechanical-score: 0.0       # Minimum mechanical adherence score
    max-preparation-score: 1.0      # Maximum preparation score cap
