spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_FILE:build/edgerush.db}
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: false

sync:
  cron: "0 0 4 * * *"
  wowaudit:
    base-url: ${WOWAUDIT_BASE_URL:https://api.wowaudit.com/v1}
    guild-profile-uri: ${WOWAUDIT_GUILD_URI:}
    api-key: ${WOWAUDIT_API_KEY:}
