spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_FILE:build/edgerush.db}
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: false

sync:
  cron: "0 0 4 * * *"
  run-on-startup: ${SYNC_RUN_ON_STARTUP:false}
  wowaudit:
    base-url: ${WOWAUDIT_BASE_URL:https://wowaudit.com}
    guild-profile-uri: ${WOWAUDIT_GUILD_URI:}
    api-key: ${WOWAUDIT_API_KEY:}
