package com.edgerush.datasync.security

import com.edgerush.lootman.api.auth.OAuth2Properties
import io.jsonwebtoken.security.Keys
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import java.security.SecureRandom
import java.util.*
import javax.crypto.SecretKey

/**
 * Provides a shared JWT secret key for all JWT operations.
 * This ensures that tokens generated by AuthenticationService can be validated by JwtService.
 *
 * The key is generated once at startup and shared across all services.
 */
@Component
class JwtKeyProvider(
    private val oauth2Properties: OAuth2Properties,
) {
    private val logger = LoggerFactory.getLogger(JwtKeyProvider::class.java)
    private val secureRandom = SecureRandom()

    /**
     * The shared JWT secret key. Generated once at startup.
     */
    val secretKey: SecretKey by lazy {
        val secret =
            oauth2Properties.jwt.secret.ifBlank {
                // Generate a random key if not configured (for development)
                logger.warn("JWT secret not configured, using random key. Sessions will not persist across restarts.")
                Base64.getEncoder().encodeToString(ByteArray(64).also { secureRandom.nextBytes(it) })
            }
        Keys.hmacShaKeyFor(Base64.getDecoder().decode(secret))
    }
}
