package com.edgerush.datasync.security

import com.edgerush.lootman.api.auth.OAuth2Properties
import io.jsonwebtoken.Claims
import io.jsonwebtoken.Jwts
import org.springframework.stereotype.Service
import java.util.*

/**
 * JWT service that uses the shared JwtKeyProvider.
 * This ensures tokens generated by AuthenticationService can be validated here.
 */
@Service
class JwtService(
    private val jwtKeyProvider: JwtKeyProvider,
    private val oauth2Properties: OAuth2Properties,
) {
    fun validateToken(token: String): Boolean {
        return try {
            Jwts.parser()
                .verifyWith(jwtKeyProvider.secretKey)
                .build()
                .parseSignedClaims(token)
            true
        } catch (e: Exception) {
            false
        }
    }

    fun extractClaims(token: String): Claims {
        return Jwts.parser()
            .verifyWith(jwtKeyProvider.secretKey)
            .build()
            .parseSignedClaims(token)
            .payload
    }

    fun extractUser(token: String): AuthenticatedUser {
        val claims = extractClaims(token)

        // Support both singular (from AuthenticationService) and plural (legacy) claim formats
        val roles = when {
            claims["roles"] is List<*> -> (claims["roles"] as List<*>).map { it.toString() }
            claims["role"] is String -> listOf(claims["role"] as String)
            else -> emptyList()
        }

        val guildIds = when {
            claims["guildIds"] is List<*> -> (claims["guildIds"] as List<*>).map { it.toString() }
            claims["guildId"] is String -> listOfNotNull(claims["guildId"] as? String)
            else -> emptyList()
        }

        return AuthenticatedUser(
            id = claims.subject,
            username = claims["username"] as? String ?: claims.subject,
            roles = roles,
            guildIds = guildIds,
            isAdminMode = false,
        )
    }

    fun generateToken(user: AuthenticatedUser): String {
        val now = Date()
        // Use accessTokenValidityMinutes converted to milliseconds
        val expirationMs = oauth2Properties.jwt.accessTokenValidityMinutes * 60 * 1000
        val expiration = Date(now.time + expirationMs)

        return Jwts.builder()
            .subject(user.id)
            .claim("username", user.username)
            .claim("roles", user.roles)
            .claim("guildIds", user.guildIds)
            .issuer(oauth2Properties.jwt.issuer)
            .issuedAt(now)
            .expiration(expiration)
            .signWith(jwtKeyProvider.secretKey)
            .compact()
    }
}
